/**
 * Message persistence with delivery guarantees.
 *
 * Two properties this layer provides, both absent from the original:
 *
 *  1. **Idempotency.** Every message carries a `client_msg_id` generated by the
 *     sender. If a client retries because it never saw an acknowledgement, the
 *     insert collides on a unique index and we return the *existing* row instead
 *     of creating a duplicate. Retrying is therefore always safe.
 *
 *  2. **Ordering and gap detection.** Each message gets a per-chat `seq` that
 *     increases by exactly one. A client that reconnects after an outage asks for
 *     "everything after seq N" and can prove it missed nothing — the mechanism
 *     that turns a dropped socket from silent data loss into an automatic
 *     backfill.
 */

const { randomUUID } = require('crypto');
const { getDb, plain, plainAll, transaction, isUniqueViolation } = require('../index');

const SELECT_COLUMNS = `
  id, chat_id, sender_id, sender_username, content, type,
  seq, client_msg_id, created_at, created_at_ms
`;

/**
 * Insert a message, assigning the next per-chat sequence number.
 * @returns {{message:object, duplicate:boolean}}
 */
function append({ chatId, senderId, senderUsername, content, type = 'text', clientMsgId = null }) {
  return transaction(db => {
    if (clientMsgId) {
      const existing = plain(
        db.prepare(`SELECT ${SELECT_COLUMNS} FROM messages WHERE chat_id = ? AND client_msg_id = ?`)
          .get(chatId, clientMsgId)
      );
      if (existing) return { message: existing, duplicate: true };
    }

    const nowMs = Date.now();
    const id = randomUUID();
    const seq = (db.prepare('SELECT COALESCE(MAX(seq), 0) AS max FROM messages WHERE chat_id = ?').get(chatId)?.max ?? 0) + 1;

    try {
      db.prepare(`
        INSERT INTO messages (id, chat_id, sender_id, sender_username, content, type, seq, client_msg_id, created_at, created_at_ms)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).run(id, chatId, senderId, senderUsername, content, type, seq, clientMsgId, Math.floor(nowMs / 1000), nowMs);
    } catch (err) {
      // Racing insert with the same client_msg_id — the other writer won; return theirs.
      if (isUniqueViolation(err) && clientMsgId) {
        const existing = plain(
          db.prepare(`SELECT ${SELECT_COLUMNS} FROM messages WHERE chat_id = ? AND client_msg_id = ?`)
            .get(chatId, clientMsgId)
        );
        if (existing) return { message: existing, duplicate: true };
      }
      throw err;
    }

    return {
      message: {
        id, chat_id: chatId, sender_id: senderId, sender_username: senderUsername,
        content, type, seq, client_msg_id: clientMsgId,
        created_at: Math.floor(nowMs / 1000), created_at_ms: nowMs,
      },
      duplicate: false,
    };
  });
}

/**
 * The most recent `limit` messages, returned oldest-first for rendering.
 *
 * The original query was `ORDER BY created_at ASC LIMIT 100`, which returns the
 * *first* hundred messages ever sent — so past a hundred messages a chat looked
 * frozen in time. Ordering by seq DESC then reversing fixes that.
 */
function recent(chatId, limit = 100) {
  const rows = plainAll(
    getDb().prepare(`SELECT ${SELECT_COLUMNS} FROM messages WHERE chat_id = ? ORDER BY seq DESC LIMIT ?`)
      .all(chatId, limit)
  );
  return rows.reverse();
}

/** Everything strictly after `seq`, oldest-first — the reconnect backfill query. */
function since(chatId, seq, limit = 500) {
  return plainAll(
    getDb().prepare(`SELECT ${SELECT_COLUMNS} FROM messages WHERE chat_id = ? AND seq > ? ORDER BY seq ASC LIMIT ?`)
      .all(chatId, seq, limit)
  );
}

/** A page of history older than `seq`, oldest-first — infinite scroll upward. */
function before(chatId, seq, limit = 100) {
  const rows = plainAll(
    getDb().prepare(`SELECT ${SELECT_COLUMNS} FROM messages WHERE chat_id = ? AND seq < ? ORDER BY seq DESC LIMIT ?`)
      .all(chatId, seq, limit)
  );
  return rows.reverse();
}

function latestSeq(chatId) {
  return getDb().prepare('SELECT COALESCE(MAX(seq), 0) AS seq FROM messages WHERE chat_id = ?').get(chatId)?.seq ?? 0;
}

function countIn(chatId) {
  return getDb().prepare('SELECT COUNT(*) AS n FROM messages WHERE chat_id = ?').get(chatId)?.n ?? 0;
}

/** Last N messages as AI context, oldest-first. */
function contextWindow(chatId, limit) {
  const rows = plainAll(
    getDb().prepare(
      'SELECT sender_username, content, type FROM messages WHERE chat_id = ? ORDER BY seq DESC LIMIT ?'
    ).all(chatId, limit)
  );
  return rows.reverse();
}

function findByClientId(chatId, clientMsgId) {
  return plain(
    getDb().prepare(`SELECT ${SELECT_COLUMNS} FROM messages WHERE chat_id = ? AND client_msg_id = ?`)
      .get(chatId, clientMsgId)
  );
}

/** Persisted read/delivery cursor, so "what did this user actually receive" survives restarts. */
function setCursor(chatId, userId, seq) {
  getDb().prepare(`
    INSERT INTO delivery_cursors (chat_id, user_id, last_seq, updated_at)
    VALUES (?, ?, ?, ?)
    ON CONFLICT(chat_id, user_id) DO UPDATE SET
      last_seq   = MAX(delivery_cursors.last_seq, excluded.last_seq),
      updated_at = excluded.updated_at
  `).run(chatId, userId, seq, Date.now());
}

function getCursor(chatId, userId) {
  return getDb().prepare('SELECT last_seq FROM delivery_cursors WHERE chat_id = ? AND user_id = ?')
    .get(chatId, userId)?.last_seq ?? 0;
}

/** Unread counts for every chat the user belongs to, in one query. */
function unreadCounts(userId) {
  const rows = plainAll(getDb().prepare(`
    SELECT cm.chat_id AS chat_id,
           COALESCE(MAX(m.seq), 0) - COALESCE(dc.last_seq, 0) AS unread
      FROM chat_members cm
      LEFT JOIN messages m         ON m.chat_id = cm.chat_id
      LEFT JOIN delivery_cursors dc ON dc.chat_id = cm.chat_id AND dc.user_id = cm.user_id
     WHERE cm.user_id = ?
     GROUP BY cm.chat_id, dc.last_seq
  `).all(userId));
  const out = {};
  for (const row of rows) out[row.chat_id] = Math.max(0, row.unread);
  return out;
}

module.exports = {
  append, recent, since, before, latestSeq, countIn,
  contextWindow, findByClientId, setCursor, getCursor, unreadCounts,
};
